### PR TITLE
Bugfix: appending lists in amendments produced broken diff (#2129)

### PR DESCRIPTION
**Pull request by CatoTH**
This solves two issues:
- https://github.com/OpenSlides/openslides-client/issues/2129
- https://github.com/OpenSlides/openslides-client/issues/1767

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Does this PR also fixes #1767?

**Comment by CatoTH** [comment]
@emanuelschuetze Now it does ;-)

**Review by luisa-beerboom — APPROVED** [review]

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
#1767 is not yet fixed.

This example in amendment detail view looks good:
amendment-detail

But the created PDF shows wrong line ("3"):
amendment-pdf


And this example from initial issue message does not work:
amendment-issue1767


The other issue #2129 is fixed and looks good!

**Comment by CatoTH** [comment]
@emanuelschuetze I fixed the second issue with the deeply nested lists (where a text replacement is done).

As for the PDF, this does not look like an issue withe the diff actually. The HTML generated and passed to `this.htmlToPdfService.convertHtml` in https://github.com/OpenSlides/openslides-client/blob/main/client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts#L636 is as follows:

```
<h3>Zeile 5</h3><div class="paragraphcontext">
<ul class="os-split-after">
<li class="os-split-after"><span class="os-line-number line-number-2" data-line-number="2" contenteditable="false">&nbsp;</span>2 
<ul class="os-split-after">
<li><span class="os-line-number line-number-3" data-line-number="3" contenteditable="false">&nbsp;</span>a</li><li><span class="os-line-number line-number-4" data-line-number="4" contenteditable="false">&nbsp;</span>b</li></ul></li></ul></div>

<ul class="os-split-before"><li class="os-split-before">
<ul class="os-split-before">
<li><span class="os-line-number line-number-5" data-line-number="5" contenteditable="false">&nbsp;</span>c</li>
<li class="insert">d</li>
</ul></li></ul>
<div class="paragraphcontext"></div>
```

That looks correct to me - the  `insert` only is at `d` (4 in your screenshot). Maybe the PDF renderer can't handle that?

**Comment by emanuelschuetze** [comment]
Rebased on top of current upstream/main branch.

Retested. Found 3 broken diffs in amendments, see screenshots:
amendment-01
amendment-02a
amendment-02b

**Comment by CatoTH** [comment]
@emanuelschuetze So I added one more fix that addresses the second issue (where the "Ebene 3" is replaced by "Ebene 3b").
When changes are made at several lines at once, I have a feeling the effort in trying to fix the issues will be completely out of proportion to how often this will actually happen and the nuisance that the current situation is. There is just too much going on in the Diff (which not only needs to work around the HTML formattings, but also the line numbers)

**Review by emanuelschuetze — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
Rebased

**Pull request merged**
