### PR TITLE
add validator for organization reply address

### LINKED ISSUE #1969: Trim whitespace in email fields
Whitespaces in email addresses should be trimmed.
In some places this is already done, but we should unify this for all email inputs.
Specially for the reply address in email settings it is missing and no mail can be sent at all if the address contains a leading or trailing whitespace.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1969

### CODE REVIEW

**Review by luisa-beerboom — COMMENTED** [review]
Adding an email validator is a good idea in general (honestly I wonder why that wasn't done from the start), but I think that we may still want to trim white spaces to counteract a certain mobile bug that causes white spaces to be added behind the input when copy/pasting into a field

**Comment by bastianjoel** [comment]
I've added a directive that trims the pasted input.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
I can still add blanks in meeting reply address (meeting participants settings), e.g. "info@example.com ".
`[{"action":"meeting.update","data":[{"users_email_replyto":"info@example.com ","id":126}]}]`

**Comment by bastianjoel** [comment]
I can't replicate that. When I'm adding a space at the end of the email address a error message is shown below the input and I can't save.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
You fixed the orga settings component only! My test was in meeting participant settings. Please fix also this email input field.

**Review by luisa-beerboom — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
