### PR TITLE
Change hyperlink style

### LINKED ISSUE #2206: Inconsistent color for hyperlinks between light/dark themes
During some testing with OpenSlides for my user base, we stumbled on this issue with the default color OpenSlides selects for themes being inconsistent between the light and dark themes. In our case, a primary color of a black from our branding guidelines has caused links to not be obvious and visible on items like the Home screen. 

Steps to Reproduce:

1. 1. Set OpenSlides colors to the following: 
  - Primary Color: 231F20
  - Accent Color: EC1F27
  - Warn Color: F06400
2. Create some example text with hyperlinks in the Home screen (or text of an agenda item or motion). 
3. Toggle between light and dark mode

Expected behavior:
Hyperlinks should be the accent color regardless of theme mode. 

Potential workaround:
Manual coloring of the text via the in-browser editor bypasses this issue but is time consuming for larger pages. 

I've attached some images of the problem on our instance!
image (6)
Screenshot 2023-04-15 at 2 11 44 PM

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2206

Changed link styles in
- legal and privacy notice
- update snackbar
- topic and election text
- motion text/change reco/reason (also for amendments)
- meeting start
- participant detail view (about me)

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Comment by luisa-beerboom** [comment]
Should pay attention on how this interacts with  #2535, may be necessary to revert a part of those changes

**Review by Elblinator — CHANGES_REQUESTED** [review]
The font-colour should still be the primary colour in light-theme and accent in dark-themed

**Review by Elblinator — CHANGES_REQUESTED** [review]
In the projector: 
A hyperlink is missing the permanent underline

In an amendment: 
If the hyperlink is one whole line and is fully deleted, then the red colour for deleted words vanishes with a reload

**The line how it should be displayed:**
Screenshot_20230904_151200


**How the same line is displayed after a reload:**
Screenshot_20230904_151333

**Review by Elblinator — CHANGES_REQUESTED** [review]
in a projector: if a message with a hyperlink is projected then the permanent underline is missing. 
The underline only appears when you hover over the hyperlink

The message should have a permanent hyperlink like the other hyperlinks

**Review by Elblinator — APPROVED** [review]
code

**Pull request merged**
