### PR TITLE
Account- and participant-lists now filter inactive correctly

### LINKED ISSUE #1014: Filters, that do not work: accounts (in-) active
The reason for this bug is, that currently, it is checked if `account.is_active === false`. However, accounts' `is_active` can be `null`, because it is not set by the datastore/backend.

### LINKED ISSUE #1038: In the participant list one cannot filter the participants by `is_present === false`
base-list-filter.service.ts

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1014 
Closes #1038

### CODE REVIEW

**Review by emanuelschuetze — APPROVED** [review]
works now.

**Review by GabrielInTheWorld — APPROVED** [review]
Fine!

**Comment by GabrielInTheWorld** [comment]
@luisa-beerboom: Does this PR also fix #1038?

**Comment by luisa-beerboom** [comment]
> @luisa-beerboom: Does this PR also fix #1038?

Yes, it does actually, I'll link it

**Pull request merged**
