### PR TITLE
Update motion workflow export

### LINKED ISSUE #2555: Add the fields `set_workflow_timestamp` and `allow_motion_forwarding` to the motion workflow export
if a workflow is exported the two options set timestamp and allow forwarding of motions are not exported. 

These two options should also be exportetd

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Close #2555

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
allow_motion_forwarding and set_workflow_timestamp are only exported if it was activated once 
It should always be exported even if it was never true

**Comment by luisa-beerboom** [comment]
The reason why this happens is because all other workflow fields have defaults set in the backend. This causes the value to be automatically set in the backend upon workflow creation, meaning that those fields will have a value, even if they were never changed.

Therefore even the fields that are off by default technically have a value at the start, except for the two new fields which have no default set and will therefore initialized without a value (which will be interpreted as "false" in the client).
Since those two fields have no value, they will not be registered by the export.

There are multiple ways in which this may be changed.
1. I could build an extra conditional into the client and add the two fields, if they are empty, or
2. The backend could set defaults for these two fields (which may require a migration to fix this problem on legacy workflows)
3. The backend could delete the defaults of all boolean fields that are false by default (which would at least create consistency in that this behaviour would now happen to all these fields)

Given that the workflow.import and all workflow-related functionality will still work perfectly fine with how the system currently is, however, I question whether it is really necessary to change anything here.

What do you think would be best @Elblinator @rrenkert

**Comment by rrenkert** [comment]
Please implement option 2.

**Review by Elblinator — APPROVED** [review]
Given the new course of action the client PR is working fine. Before merging however the back-end should be adjusted

see https://github.com/OpenSlides/openslides-backend/issues/1930

**Review by bastianjoel — APPROVED** [review]

**Comment by jsangmeister** [comment]
Do we really want to add a migration for this? It feels like a huge overhead when the client could just fill in empty boolean fields with `false` by default, considering how long our migrations take, especially on big instances.

**Pull request merged**
