### PR TITLE
Redesign election ballots

### LINKED ISSUE #2128: Redesign election ballot
The ballot for elections should be redesigned. See following mockups:

Meeting Admin view includes progress:
20230214JaNeinEnthaltungAdmin

Delegates view:
20230214JaNeinEnthaltung

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2128 

- [x] Zebra layout for list (i.e. grey background for every other line)
- [x] strike text in red
- [x] Vote area should probably vanish along with the "send vote" button if vote has been sent

### CODE REVIEW

**Comment by Elblinator** [comment]
This should be reevaluated and then a new PR should be created

**Comment by luisa-beerboom** [comment]
I actually managed to update this, so - reopened!

Still needs work though

**Comment by Eich-hoernchen** [comment]
This is the new election icon. It's a drawn cross. YES -> green, NO -> red and ABSTENTION -> darker gray. The circle mark is in light gray at the start. The circle mark turns dark if the button will be clicked and the cross will appear in the given color for YES, NO or ABSTENTION.

election_icon

**Comment by emanuelschuetze** [comment]
as discussed last week

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
as discussed:
* structure level is missing in ballot
* mobile theme for ballot required

**Review by emanuelschuetze — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Pull request merged**
