### PR TITLE
In organization settings edit only send values that have been changed

### LINKED ISSUE #2476: Organization settings sends values for fields that haven't been changed
This can cause problems if a specific field is not being processed correctly, as an unacceptable value for it will be sent to the backend, even if it has not been changed, potentially causing all attempts to change other fields to fail as well.

While fixing this the bug, where the content of the attribute mapping field, if left blank, is not replaced with null, should also be fixed. This replacement should, of course, harmonize with the change detection.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Also made sure that the SSO config is replaced with null if the new value is an empty value

Closes #2476

### CODE REVIEW

**Review by Elblinator — APPROVED** [review]
code-review

**Review by rrenkert — CHANGES_REQUESTED** [review]
After clearing the saml_attr_mapping reverting chenges does not work anymore:

ERROR TypeError: Cannot read properties of undefined (reading 'split')
    at OrganizationSettingsComponent.updateForm (organization-setting…component.ts:126:43)
    at OrganizationSettingsComponent.revertChanges (organization-setting…component.ts:107:18)

Same error appears on save, but does not prevent saving.

**Comment by luisa-beerboom** [comment]
> After clearing the saml_attr_mapping reverting changes does not work anymore:
> 
> ERROR TypeError: Cannot read properties of undefined (reading 'split') at OrganizationSettingsComponent.updateForm (organization-setting…component.ts:126:43) at OrganizationSettingsComponent.revertChanges (organization-setting…component.ts:107:18)
> 
> Same error appears on save, but does not prevent saving.

What do you mean by "clearing the saml_attr_mapping"?

**Comment by rrenkert** [comment]
> What do you mean by "clearing the saml_attr_mapping"?
I removed the content and saved the settings.

**Review by rrenkert — APPROVED** [review]

**Pull request merged**
