### PR TITLE
Update mdc dialog component

### PR DESCRIPTION
**Pull request by reiterl**
Migration of the ng material legacy dialog component.

### CODE REVIEW

**Review by Elblinator — CHANGES_REQUESTED** [review]
weird-ui bugs:
- global search component: now has two (1x horizontal, 1x vertical) scroll bar, and the close X glitches in the right top corner
- new design dialog in os-theme-list: the closing x is too close to the right border
- 'project selection?'-dialog the title from the to be projected opject glitches to the left border of the dialog, the distance between the different projectors and between the mat-divider is too small
- poll-dialog every mat-form-field and mat-checkbox needs to have a padding or margin to the left/right dialog-border
- edit dialog for topic: everything needs to have more padding or margin to the borders
- export motion-dialog: the vertical scrollbar is new and should be prevented
- edit projector-dialog the left side of the dialog (information not preview) are not scrollable anymore
- organisation-level new tag/edit tag dialog: the dialog is too wide, and the generate new color button is not fully visible
- connect 4 and chess dialogtitle and clear X is too low

**Comment by reiterl** [comment]
I won't continue here.

**Comment by bastianjoel** [comment]
Did you just ran the automatic migration here or did you do any manual changes? In case you just applied the automatic migration please close this PR.

**Comment by reiterl** [comment]
Closed, because it was only automatic migration to mdc.

**Pull request closed without merging**
