### PR TITLE
Remove archive banner (#796)

### LINKED ISSUE #796: After signing out, the banner "Archived" is displayed

### PR DESCRIPTION
**Pull request by bug0002**
Fixes #796

### CODE REVIEW

**Review by GabrielInTheWorld — CHANGES_REQUESTED** [review]
The code looks good!
Two remarks:
1. Change the title, so the number of the related issue is not shown or in paranthesis linked (by a `#`)
2. Write in the description something like "Fixes #...", so everyone knows what this PR will solve

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Tested: archive banner is still visible after logout.

**Comment by bug0002** [comment]
First review request should be done. Second : can confirm the issue...

**Comment by bug0002** [comment]
Debugging, keeping notes :

    public clear(): void {
        console.log('clear');

so that the message "clear" is displayed when the clear function is called

and

    public addBanner(toAdd: BannerDefinition): void {
        console.log('addBanner', toAdd);

When reproducing the issue, it becomes obvious that addBanner is called after clear (on devtools console), resulting in above.

Further :

addBanner appears in two files, banner.service.ts (definition), and active-meeting.service.ts where the setupActiveMeeting function is relevant

**Pull request closed without merging**
