### PR TITLE
Some fixes amendment detail change recommendation

### PR DESCRIPTION
**Pull request by reiterl**
The motion detail with the line numbering is difficult.

This pull request should solve case A and B1 from #2946 
But there are still some strange behaviour in there.

### CODE REVIEW

**Review by Elblinator — CHANGES_REQUESTED** [review]
B1 is fixed 

If the amendment has a change recommendation only the line with change recommendation is now displayed in the diff version:

**Comment by reiterl** [comment]
I can see that, but it is the amendment diff displayed. I just set diff mode. These components are cans of worms.

**Comment by reiterl** [comment]
I won't continue here.

**Comment by bastianjoel** [comment]
Please update your PR to just fix part of the issue and maybe remove regressions, close it or provide further detail on how we should proceed with this.

**Comment by reiterl** [comment]
As I won't continue here, I close this pr.

**Pull request closed without merging**
