### PR TITLE
meeting edit bugs

### LINKED ISSUE #1432: Several bugs in meeting edit page
The meeting edit page has several errors.

**Admin and Participant line:** 
Normally users that exist at the account level should be able to be found and added by entering their username. This does not work. There are several problems here:

- [x] Users are partially not found. Example: https://testintern.openslides.com/committees/2/meeting/edit/2 try to add Emanuel in participants. One of two possible users is displayed.
- [x] If a user is selected, he/she will not be displayed in the row

<s>**Save-Button**
- [ ] When save is clicked, a forwarding to the committee overview takes place</s>

**Reproduction row problem** 
1. login as a superadmin
2. open a committee
3. open the edit mode of a meeting (three-dot-menu/edit)
4. add existing users in the row participants and administrators. 

**What should happen:** 

Rows
- Existing user should be found and could be added in the rows by typing the correct username. Additionally the row should display all selected users.

<s>Save-Button
- Click should save content, but doesn't redirect. Closing could be done by clicking on X. </s>

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1432 #1502
closes #1700

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to add participants/admins in meeting update view as user with CML (committee admin):
-> error: Missing OrganizationManagementLevel: can_manage_users

**Comment by emanuelschuetze** [comment]
Is it really useful on performance reasons to show all accounts in the search value selector (for orga admins)? We removed this feature for some month to increase the client performance...

**Comment by bastianjoel** [comment]
Currently without adding the full account list to the input it is not possible to see who is selected.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to remove a selected user/admin user from meeting edit view -> nothing happens.
Adding users/admins works as expected. But removing action does not save changes.

**Comment by bastianjoel** [comment]
Works for me

**Comment by emanuelschuetze** [comment]
Try to test this:
- create new meeting as superadmin
- create new users in meeting: userA + userB
- now go to meeting edit view -> minor error: users field is empty (but after click into field userA and userB is visible)
- remove userB and save -> now userB is successfully removed. Ok, seems to work.

But if you edit an existing meeting (e.g. OpenSlides Demo in dev mode):
- try to remove user "a", save -> "a" was not removed from meeting

**Review by luisa-beerboom — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
