### PR TITLE
Change Arrow behaviour in motion-detail

### LINKED ISSUE #2424: Change of arrows in motion-view
Where: in the motion-view while being in the detail-view of one motion 

In the desktop view two arrows can be used directly to switch between the different motions: 
motion-arrows

in the tablet and phone view these arrows move into the three-dot-menu:
motion-arrows-small

Wanted behaviour: 
The arrows should not move to the three dot menu, regardless of the display size
In the tablet-view the arrows should be like the arrows in the desktop-view
In the phone view the arrows should stay where they are but lose the describer (in the pictures 15-Ä01 and R01-Ä02)

### PR DESCRIPTION
**Pull request by Elblinator**
Closes #2424

I took the liberty to change the appearance in a different way. 
Could the testers please state if the new behaviour is still inline with the wanted behaviour (to make the handling on the phone easier)

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Comment by MSoeb** [comment]
In general the buttons works as they should. But there is small layout issue with small mobile devices in portrait mode. The buttons are quite large in portrait mode. @Elblinator let's check this. Maybe we can optimize this.

**Review by bastianjoel — APPROVED** [review]

**Comment by Elblinator** [comment]
verbal rewiev from @MSoeb 
Tablet-view is fine.
In the phone view: only the arrow should be displayed

**Review by bastianjoel — APPROVED** [review]

**Review by MSoeb — CHANGES_REQUESTED** [review]
image

First: It works as it should. Small improvements needed. 

- [ ] The distance/space between the navigation buttons in mobile view is a to wide. They should be placed a bit nearer. 
- [ ] The desktop view has a slightly different navigation layout, which made the describer "jump". This feels strange. Does this happens because of the wider space on mobile view? (@Elblinator I will show it to you)

**Review by bastianjoel — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Review by MSoeb — APPROVED** [review]
Works as intended.

**Review by MSoeb — APPROVED** [review]
Works as intended.

**Pull request merged**
