### PR TITLE
Fix for meeting settings default groups

### LINKED ISSUE #3382: Fix resetting 'Default groups with voting rights'
**Current behaviour:**
If the 'Default voting type' or 'Add to agenda' is changed then every entry from 'Default groups with voting rights' is deselected

**Reproduction:**
1. navigate to Settings -> continue to Agenda/Motions/Elections
2. select anything in 'Default groups with voting rights'
3. save the change
4. change 'Default voting type' (in Motions and Elections) or 'Add to agenda' (in Agenda)
5. save the change
6. the old default groups are still displayed
7. reload page
8. the default groups are empty

**Example payload from election:**
```
[
    {
        "action": "meeting.update",
        "data": [
            {
                "assignment_poll_default_group_ids": null,
                "assignment_poll_default_type": "pseudoanonymous",
                "id": 2
            }
        ]
    }
]
```

**Wanted behaviour:**
The 'Default groups with voting rights' should not ne automatically changed. They should stay the same even if other settings are changed

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #3382

### CODE REVIEW

**Review by Elblinator — APPROVED** [review]
function

(I tried to test several case,, and could not find any bug)

**Review by bastianjoel — COMMENTED** [review]
I am not sure about this. The `_comparedForm` part looks very odd to me. Also the distingUntilChanged check stands in contradiction with the check within the subscription. 

@luisa-beerboom introduced the `_comparedForm` in #2103 where I was not involved. Maybe she can give better input on this.

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]
This is just going to cause `onChange` to not be called with `groups` type fields.

At this point lines 229 to 231 is pointless and the `groups` section of `onChange` will not even get called. Due to the latter this component will never send an update event, leading me to question, if changes made to group fields will even get passed on to the backend.

Please check/fix that.

**Comment by reiterl** [comment]
As far as understand the code, the `_compareForm` flag is set, after the first compare. So the onChange code is used then, because `_compareFlag` is true. @luisa-beerboom  can you verify this?

**Comment by luisa-beerboom** [comment]
Ah right, my bad.
I think this looks fine then.

**Review by luisa-beerboom — APPROVED** [review]

**Pull request merged**
