### PR TITLE
Add new options for editing speaking time

### LINKED ISSUE #3296: Speaking times widget: Enhance time edit menu
**Description**: In the current state, the three-dot-menu behind a structure level misses some time edit options,which leads to some problems. 
- If someone has spoken, the time can't be edit. This results in the worst case scenario, that the list of speakers needs to be created again from the scratch.
- If there is a need to add, remove or reset the time, the menu doesn't provide the edit options.

image

**What should happen:**
- [x] Editing total time should always be possible. The 'edit total time' options should always be active/enabled. 
- [ ]  Additionally other edit time options should be added, which should always be active. This include three options: 
1. Reset timer: The timer should be resetable to the start time of the set structure level timer. NOT the general default time value for structure levels. 
2. Add time option: It should be possible to manually add time to the structure level timer. 
3. Remove time option: It should be possible to manually remove time from the structure level timer.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #3296

### CODE REVIEW

**Comment by Elblinator** [comment]
https://github.com/OpenSlides/openslides-backend/issues/2219 is needed for this to work

**Review by bastianjoel — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Comment by luisa-beerboom** [comment]
@Elblinator
You, @jsangmeister and I need to talk about the requirements for this issue in the near future, because there is some confusion on what is supposed to happen on the backend side

**Review by Elblinator — CHANGES_REQUESTED** [review]
Please also change the text 'Remove' to "Subtract" inside the dialog

besides that: it looks great!

**Review by Elblinator — APPROVED** [review]

**Comment by Elblinator** [comment]
please merge when the backend is also ready :) 
https://github.com/OpenSlides/openslides-backend/issues/2219

**Pull request merged**
