### PR TITLE
Add workflow and group settings help texts

### LINKED ISSUE #2352: Helps text for group permissions and workflows in OpenSlides
`.../.../participants/groups`
`.../.../motions/workflows/...`

### Feature description

- The example of group rights shows how the help text works/looks.
- If the mouse cursor is hovered over the first column (Permissions) in the group permissions or in the first column in the workflows, a question mark appears: in CSS → cursor: help; (appearance depends on the operating system).
- The font (name of the first column, e.g. "Can see projector") is coloured an 80% GREY as long as the cursor is on it. (no link/underlining, no button/key colouring as "only" help text and no action follows).
- After clicking on the label, the help text appears aligned at the bottom right corner of the cursor. See screenshot.
 (or space bar? → check)
- The help text box is a maximum of 250 - 300 px wide. The box is hidden when you leave the area of the respective designation (without clicking, just move the mouse).
- If possible, consider paragraphs and formatting of the text.

### Notes
- For easier handling, we have created a table: [Sammlung-Hilfetexte.ods](https://github.com/OpenSlides/openslides-client/files/11625190/Sammlung-Hilfetexte.ods)
- Please consider the updated order of permissions in the first column.
- There are priorities for the permissions (1 first, then 2 and so on, changes are marked in yellow).
- The permission "Can manage logos and fonts" should be placed under the category "Files", as you need to be able to see files in order to manage logos and fonts.

### Questions?
→ Contact Katharina & Martin

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2352

### CODE REVIEW

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]

**Review by luisa-beerboom — APPROVED** [review]

**Comment by jsangmeister** [comment]
please stick to https://github.com/OpenSlides/OpenSlides/wiki/Development-organization#pull-request-titles-and-commit-messages

**Comment by MSoeb** [comment]
Updated help text list. Please take care, most German and English tool tips have been changed.  
[2023-06-07_Sammlung-Tooltips.ods](https://github.com/OpenSlides/openslides-client/files/11675111/2023-06-07_Sammlung-Tooltips.ods)

**Comment by bastianjoel** [comment]
As of now hyperlinks (or to be more specific html content) are not possible within the tooltips provided by Angular Material. Therefore we would need to implement something ourselves there if we want to use hyperlinks. 

Would it be possible to provide text without hyperlinks or is this a requirement?

**Comment by MSoeb** [comment]
Hyperlinks would be nice to have, but if the implementation requires too much effort and time, we don't need to implement them. Just add the rest of the text without the brackets with hyperlinks.

**Comment by bastianjoel** [comment]
> Hyperlinks would be nice to have, but if the implementation requires too much effort and time, we don't need to implement them. Just add the rest of the text without the brackets with hyperlinks.

I removed the hyperlinks from the texts.

**Review by emanuelschuetze — APPROVED** [review]
Please resolve conflict and merge.

**Pull request merged**
