### PR TITLE
Handling of deleted candidates

### LINKED ISSUE #1676: Implement handling for assignment candidates without users
# Changes to `models.yml` have just been added to OpenSlides

Please acknowledge the recent changes to `models.yml` and update your projects accordingly.

### Corresponding Commit:

[0c70263980ff1ca1dfd346abde156e32720662c5](https://github.com/OpenSlides/openslides-backend/commit/0c70263980ff1ca1dfd346abde156e32720662c5)

### Client

https://github.com/OpenSlides/openslides-client

### Autoupdate

https://github.com/OpenSlides/openslides-autoupdate-service

### Manage

https://github.com/OpenSlides/openslides-manage-service

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1676 

Truthfully the client already could display deleted users as candidates just fine, but this one function was a bit clumsy so I fixed it

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to open an assignment poll detail view with an deleted candidate name:
`TypeError: Cannot read properties of null (reading 'getFullName')
    at AssignmentPollDetailComponent.getMethodYVoteLabel (assignment-poll-detail.component.ts:152:38)`

**Review by bastianjoel — APPROVED** [review]

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
* Create new assignment
* Add new candidate
* Create ballot
* Delete candidate account
* Now try to remove the "Deleted candidate" box in candidate list
=> Backend shows KeyError: 'user_id'

**Comment by luisa-beerboom** [comment]
> * Create new assignment
> 
>     * Add new candidate
> 
>     * Create ballot
> 
>     * Delete candidate account
> 
>     * Now try to remove the "Deleted candidate" box in candidate list
>       => Backend shows KeyError: 'user_id'

Looks like a backend problem to me

**Comment by luisa-beerboom** [comment]
> * Create new assignment
> 
>     * Add new candidate
> 
>     * Create ballot
> 
>     * Delete candidate account
> 
>     * Now try to remove the "Deleted candidate" box in candidate list
>       => Backend shows KeyError: 'user_id'

Solved in OpenSlides/openslides-backend#1508

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
