### PR TITLE
Fix ellipses in list title columns

### LINKED ISSUE #2100: The name colums of most lists don't show ellipses for long content
In the account list, if the name gets to long it will be cut off with an ellipsis (`…`). This _should_ happen for the name columns in all list views but is currently broken in most of them (f.E. it's broken in  the motion, topic and election lists).

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2100

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — COMMENTED** [review]
@emanuelschuetze Should the motion-block-title be elipsed after a certain character limit in a motion-list?
motion-title-in-motion

**Review by Elblinator — CHANGES_REQUESTED** [review]
if a motion title is too long it is correctly ellpised but it pushes the option out of frame and changes their theme
short title:
motion-blcok-short-title
long title: 
motion-block-long-title

**Comment by luisa-beerboom** [comment]
That's the bug from issue  #2339 
It will be fixed somewhere else (probably in PR #2349)

**Comment by emanuelschuetze** [comment]
> @emanuelschuetze Should the motion-block-title be elipsed after a certain character limit in a motion-list? motion-title-in-motion

@Elblinator Yes, please add new issues for this.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
* Create new topic item with long title
* reload agenda -> topic title shows "..."
* now open topic detail and go back to agenda
=> topic title has no "..." any more, reload helps to get "..." back

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
