### PR TITLE
Fixed bug in mass meeting assignment

### LINKED ISSUE #1441: Set meeting for a user on account level via multiple selection overwrites group inside the meeting
If a user exists in a meeting and is added to the same meeting again at the dashboard level via multiple selection, the previous group assignment is overwritten.

This is very problematic, especially for administrators, as it causes them to unintentionally lose their status.

Reproduction: For testing is a committee with a meeting needed.
1. open meeting, go to participants, create a new one and add it to group admin
2. open in new tab the dashboard and head to accounts
3. open the three-dot-menu and choose mulitselect. 
4. search for the desired user in search box, select user, click again on the three-dot-menu, choose set/remove meeting and set user to the meeting which is open in other tab
5. open other tab again, go to participants in navigation bar and check the group of the user. 

What should happen: When multiple selections are made, there should be a check that prevents the accounts from being added again, thus preventing them from being overwritten. Groups shold not be overwritten for user that exist in meeting.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1441

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]
Note: This is my proposed solution from https://github.com/OpenSlides/openslides-client/issues/1441, not the initial proposal from @MSoeb. But that's fine by me.

**Comment by MSoeb** [comment]
Fix didn't work. Group is still overwritten.

Additionally: If you want to add participants to a meeting via accounts, this is no longer possible. Existing groups are no longer recognized. An error appears: Fehler: Didn't find a group with groupname Delegierte in any meeting.

**Comment by MSoeb** [comment]
Fix didn't work. Group is still overwritten.

Additionally: If you want to add participants to a meeting via accounts, this is no longer possible. Existing groups are no longer recognized. An error appears: Fehler: Didn't find a group with groupname Delegierte in any meeting.

**Review by m-schieder — APPROVED** [review]

**Comment by luisa-beerboom** [comment]
Still can't reproduce any sort of group overwriting in the newest version. Can you perhaps try it again and see if you are doing anything special @MSoeb ?

**Comment by MSoeb** [comment]
Tried it again, works as it should.

**Review by MSoeb — APPROVED** [review]

**Pull request merged**
