### PR TITLE
Add public access orga setting

### LINKED ISSUE #4204: Public Access: Add a new setting for global activation
**Current behavior**
The new public access feature misses an additional setting for the superadmin to activate/deactivate the public access globally. 

**Wanted behavior**
A new setting should be placed on organization level in settings > Superadmin settings > under 'enable chat globally'. Name of the setting should be 'Enable public access globally'. By activating it, the option to set a meeting as public access should be avaible in any meeting. If deactivated, the setting in the meetings should not be visible.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #4204

### CODE REVIEW

**Review by reiterl — APPROVED** [review]
LGTM

**Comment by Elblinator** [comment]
After activating the setting once and then reloading the setting looks deactivated again.

**Comment by Elblinator** [comment]
- If the global setting is disabled please hide the icons "public" -> please hide the indicator that a meeting is public
- Please hide the login as a guest user button in the login mask

**Comment by Elblinator** [comment]
Also move the setting "Meetings can be public" to the Superadmin settings below: "Enable chat globally"
connected with this please hide the setting for non-superadmins

**Review by Elblinator — APPROVED** [review]

**Pull request merged**
