### PR TITLE
fix scroll position restore if scrollViewport not available yet

### LINKED ISSUE #1436: Scroll position problems: on dashboard level lists scroll position save didn't work / error message in console
Two problems occur in relation to scroll position issue #1380 

- [ ] same problem like in the mentioned issue #1380. difference is only the level. here it affects the dashboard level lists. i assume, that all lists on this level are affected.
- [ ] The second problem is an error message in the console, which currently generates no apparent problems. The error probably occurs when a list view contains few objects. 
- Example on page: https://testintern.openslides.com/70/motions. Open console and navigate to participants and back to motions. 
- The error message is: ERROR TypeError: Cannot read properties of undefined (reading 'measureScrollOffset')

What should happen: 

- Dashboard lists should have the possibility to save the scroll position like meeting lists
- no error message in console

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves  #1436

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]
not tested

**Comment by MSoeb** [comment]
fix don't work: issue still exists for lists committees and accounts on dashboard level.

**Comment by bastianjoel** [comment]
Committee and accounts use different list components. I will have a look if it makes more sense to change the used component or to implement the position restore functionality for that lists too. 

Nevertheless I would still suggest merging this PR even without that change as it fixes some newly introduced issues when accessing other lists.

**Comment by bastianjoel** [comment]
Works now for committee and accounts list

**Review by MSoeb — APPROVED** [review]

**Review by m-schieder — APPROVED** [review]

**Pull request merged**
