### PR TITLE
Make duplicate-from mandatory, if 'required_duplicate_from' is set

### LINKED ISSUE #3804: Meeting.create: make duplicate from (optionally) mandatory
Context: The new setting from the Meta-Issue https://github.com/OpenSlides/openslides-meta/issues/125

**Desired behaviour:**

- [ ] The new setting should be a checkbox: Orga-level > general > last point
- [ ] The title should be „Activate require templates for creating a meeting"
- [ ] There should be a mat-hint „If this setting is active committee-admins can only create meetings from public meeting templates, to enable these admins to create a meeting you need to create a template meeting first“
- [ ] If the setting is activated then **committee admins** while creating a meeting:
      - should only see templates in the dublicate from field
      - the dublicate from field should be mandatory -> users should not be allowed to save without sth being selected in the form-field

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #3804 

Needs https://github.com/OpenSlides/openslides-backend/pull/2524
and an updated autoupdate service

### CODE REVIEW

**Comment by Elblinator** [comment]
the issue from the autoupdate
https://github.com/OpenSlides/openslides-autoupdate-service/issues/959

**Comment by Elblinator** [comment]
I'm testing this right now, but please fix the tests

**Comment by reiterl** [comment]
I think, for the tests this needs the backend and meta pr merged.

**Review by luisa-beerboom — APPROVED** [review]

**Comment by Elblinator** [comment]
A change request:
- A committee admin should be able to set themselves as a meeting admin even if this setting is activated
Reproduction:
1. Create a meeting where the committee admin is not an admin from the meeting 
2. activate the new setting
3. login as the committee admin
4. start editing this meeting
5. you can select yourself as an admin but you cannot save the meeting

Some requirements were not documented and now need some implementing in this PR:
If the new setting is activated then (only for the committee admin)....
- The button to turn a meeting into a template/ turn a meeting not into a meeting should be hidden
- The option to duplicate a meeting should be hidden

**Comment by reiterl** [comment]
I have worked on the three points of the CR. That should be fixed. Please test/review.

**Review by Elblinator — CHANGES_REQUESTED** [review]
- The orga-admin cannot save the new setting

**Comment by reiterl** [comment]
Fix the problem with orga admins cannot save the "require_duplicate_from" setting.

**Review by Elblinator — APPROVED** [review]

**Review by luisa-beerboom — APPROVED** [review]

**Review by MSoeb — CHANGES_REQUESTED** [review]
Issue I've found:
- [ ] Meeting creation with or without the new function activated creates two error messages in the console. The creation works, but the creation mask isn't closed after saving it. Tried it as superadmin and committee admin. Doesn't worked properly for both admins.

Here the error messages:
image

Reproduction as superadmin:
1. open committee > create a committee
2. open dev-console 
3. create a meeting in the committee -> error messages will appear and the creation doesn't closed automatically.

What should happen:
1. Creation mask should close itself by saving it and open the committee detail page 
2. error messages should not appear in console

------

Please change the texts of the new function from 
- "Activate require templates for creating a meeting" to 'Enable meeting creation from templates only'
- 'If this setting is active committee-admins can only create meetings from public meeting templates, to enable these admins to create a meeting you need to create a template meeting first' to 'If this setting is activated, public meeting templates must have been created, as committee administrators can only create meetings based on public templates.'

**Review by MSoeb — CHANGES_REQUESTED** [review]
Loading bugs are gone, but the text ajdustments need to be done. They are located in the general instance settings:

- [ ] "Activate require templates for creating a meeting" to 'Enable meeting creation from templates only'

- [ ] 'If this setting is active committee-admins can only create meetings from public meeting templates, to enable these admins to create a meeting you need to create a template meeting first' to 'If this setting is activated, public meeting templates must have been created, as committee administrators can only create meetings based on public templates.'

----

Additionally: 
If the setting is activated and a committee admin wants to create a meeting from templates, a non-essential element, a dash, is displayed in the 'Duplicate from' selection. I have circled these in red in the image below.

image

What should happen?
If the new setting is activated, committee admins should only see templates in the 'Duplicate from' selection, all other information can be deleted as it is unnecessary. Specifically: Please delete the dash option.

**Comment by reiterl** [comment]
Deactivate the includeNone option of the meeting selector.

**Comment by reiterl** [comment]
Please review again.

**Review by luisa-beerboom — APPROVED** [review]

**Review by Elblinator — APPROVED** [review]
@MSoeb changes were made and I will dismiss his CR

**Comment by reiterl** [comment]
Are the AU and meta merges missing?

**Pull request merged**
