### PR TITLE
Update global search to show marks bolder

### PR DESCRIPTION
**Pull request by reiterl**
Resolves "the searched word is not bold (good first issue)" of #2738

Global search result title are no longer `marked`.
`mark` tags are now bolder.

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — DISMISSED** [review]
Some of the titles are still not bold (Agenda, Motion, Election, File

**Comment by bastianjoel** [comment]
The marks should not be visible in titles as far as I undestood.

**Comment by Elblinator** [comment]
After reconsidering the desired Thanks for pointing that out 
I'll update the change request accordingly

**Review by Elblinator — CHANGES_REQUESTED** [review]
If an account is found, then the part of the account which matched with the searched word is bold. 
The titles of the results should not be bold

**Comment by reiterl** [comment]
Add code to prevent marking in account case.

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — APPROVED** [review]
function

**Pull request merged**
