### PR TITLE
Some enhancements for committees and meetings

### LINKED ISSUE #835: Implement "Creating a meeting from a template"

### LINKED ISSUE #869: Move template meeting relation to organization
# Changes to `models.yml` have just been added to OpenSlides

Please acknowledge the recent changes to `models.yml` and update your projects accordingly.

### Corresponding Commit:

[49a608ff81bc22a956bb8f17d6d157c9fe443f75](https://github.com/OpenSlides/openslides-backend/commit/49a608ff81bc22a956bb8f17d6d157c9fe443f75)

### Client

https://github.com/OpenSlides/openslides-client

### Autoupdate

https://github.com/OpenSlides/openslides-autoupdate-service

### Manage

https://github.com/OpenSlides/openslides-manage-service

### LINKED ISSUE #937: Pass the `translate.instant` function down to the `ImportStepDescriptor`
- The `BaseImportHandler` should demand the function `translate.instant` in any way (the whole translate-service should not be passed)
- The config for the handlers is a good place, but it should not be required there, so in other services an error message won't appear

### LINKED ISSUE #977: Forwarding of a motion crashes its and the forwarded one's detail-view
- [ ] A fix would be to map an object clearly to its `meeting_id/sequential_number`.
- [ ] Ensure also that a forwarded/received motion does not enter the motion list in a meeting which is not related to the motion.

### LINKED ISSUE #983: For committee csv import: Managers of a meeting can be provided

### LINKED ISSUE #991: Improve the csv import for committees to create a meeting based on a template

### LINKED ISSUE #1008: Implement new permissions and update actions accordingly
# Changes to `permission.yml` have just been added to OpenSlides

Please acknowledge the recent changes to `permission.yml` and update your projects accordingly.

### Corresponding Commit:

[278e6fba6d0aa00633f8b22efaa10ef907c82a1a](https://github.com/OpenSlides/openslides-backend/commit/278e6fba6d0aa00633f8b22efaa10ef907c82a1a)

### Client

https://github.com/OpenSlides/openslides-client

### Autoupdate

https://github.com/OpenSlides/openslides-autoupdate-service

### Manage

https://github.com/OpenSlides/openslides-manage-service

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
- Improves the csv import for committees (Fixes #983, Fixes #991)
- Meetings can be cloned based on a template (Fixes #835, Fixes #869)
- The translate function is passed down to the ImportStepDescriptor (Fixes #937)
- Motions can only be forwarded if a user has the permission `motion.can_forward` and it is in a state, which allows this (Fixes #1008)
- Maps a model to its `<meeting_id>/<sequential_number>` (Fixes #977)

### CODE REVIEW

**Comment by GabrielInTheWorld** [comment]
There are some things we have to discuss:
- Some UI
- If we wait for OpenSlides/openslides-backend#1298

**Comment by GabrielInTheWorld** [comment]
Currently, there is no other option to pass a meeting admin for a meeting, which will be cloned.

**Comment by GabrielInTheWorld** [comment]
Waiting for OpenSlides/openslides-backend#1306.

**Comment by GabrielInTheWorld** [comment]
Still open: #1008.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
This PR looks good. Only one issue (which could be split out):
Try to create a new meeting by cloning another meeting as normal committee manager (or superadmin).
=> There are no meeting listed in the drop down menu ("Duplicate from..."). No active meeting. No template meeting.

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
