### PR TITLE
fix single votes and entitled users tables

### LINKED ISSUE #2173: Single votes and entitled users tables break when scrolling
In polls when viewing the entitled users and scrolling in that list the list behaves weird.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2173

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

**Comment by luisa-beerboom** [comment]
Seems sensible but does this affect any other lists?

**Comment by bastianjoel** [comment]
> Seems sensible but does this affect any other lists?

No

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
I run into this typeerror if I open the entitled users table of an old motion poll:

```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at entitled-users-table.component.ts:23:50
```
(same in current main)

**Comment by bastianjoel** [comment]
I cannot replicate this. But as this is not related to the original issue I would suggest opening another issue for that.

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
