### PR TITLE
Add new user permissions

### LINKED ISSUE #3158: Add new user permissions
see https://github.com/OpenSlides/openslides-backend/issues/2122, which must be implemented first

The new permissions must be implemented in the permission matrix. The update of participants should be made possible with only `user.can_update`.

### PR DESCRIPTION
**Pull request by jsangmeister**
resolves #3158

AU and backend are already merged.

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by rrenkert — CHANGES_REQUESTED** [review]
The permission `user.can_see_personal_data` was renamed in the backend and autoupdate-service. This is missing here.

**Comment by jsangmeister** [comment]
> The permission `user.can_see_personal_data` was renamed in the backend and autoupdate-service. This is missing here.

Sorry for that, seems like I missed that last time around. Now everything should be working.

**Comment by emanuelschuetze** [comment]
Error - Can't test it:

```
Error: src/app/domain/definitions/permission.config.ts:221:35 - error TS2339: Property 'userCanSeePersonalData' does not exist on type 'typeof Permission'.
client-1            | 
client-1            | 221                 value: Permission.userCanSeePersonalData
```

**Comment by jsangmeister** [comment]
Should be fixed now

**Comment by jsangmeister** [comment]
To implement/check:
- [ ] With `can_see_sensitive_data`, the following fields should be visible in the detail view:
  - [ ] `email`
  - [ ] `last_email_sent`
    - [ ] Should also be visible via icon in the list view
  - [ ] `username`
  - [ ] `saml_id`
- With `can_update` in the user detail view:
  - [ ] all data should be visible
  - [ ] the edit pen should be visible and clickable
  - [ ] all other actions (except delete) should be visible and executable (change password etc.)

Restrictions: users with `can_update` should NOT be able to create or delete groups or change the permissions of groups/structure levels (but should be able to update the group/structure level memberships of a user).

**Comment by reiterl** [comment]
It is not permitted with `user.can_update` to set a password. This is a backend bug. @jsangmeister  please fix this.

**Comment by reiterl** [comment]
I fixed some problems and introduced in `isAllowed` the field seeSensitiveData.

**Comment by jsangmeister** [comment]
> It is not permitted with `user.can_update` to set a password. This is a backend bug. @jsangmeister please fix this.

This was implemented in https://github.com/OpenSlides/openslides-backend/pull/2322. Maybe @luisa-beerboom can take a look, but please provide a more detailed error description

**Comment by reiterl** [comment]
I logged in as user with can_update in meeting A. I go to meeting A and go into the detail view of another participant and use the change password action in the menu. I get an error message.

The error message is the following:
Error: You are not allowed to perform action user.set_password. Missing permissions: OrganizationManagementLevel can_manage_users in organization 1 or CommitteeManagementLevel can_manage in committee 1 or Permission user.can_manage in meeting 2

**Comment by reiterl** [comment]
Another problem, a user with the "can update" permissions, cannot set a structure level to another user of the meeting. Error message: "Error: You are not allowed to set present.". The user hasn't the can change present
perm and hasn't changed the present checkbox.

**Comment by reiterl** [comment]
Waiting for the backend issues to be fixed.

**Comment by reiterl** [comment]
Updated the stack to current version. Now, I don't see the change password perm error anymore. Good.

**Comment by reiterl** [comment]
I am not sure about the handling of `is_present` for an user with can_update. 
Should the `can_update` permission always include the `can_manage_presence`?

**Comment by reiterl** [comment]
I talked with @rrenkert  and @MSoeb  about this pull request.
If a user has the permissions `can_update`, the user is allowed to change personal and meeting fields in the edit dialog, except `is_present`.
To change the `is_present` status, s.o. needs `can_manage_presence`.

**Comment by MSoeb** [comment]
One change request: If the user has the permission 'can update user' and "can set presence" the presence box in the user detail view is not clickable. It is grayed out. With both permissions, the user should have the ability to change the presence status in the user detail view.

Hint: Setting presence in other scenarios works fine.

**Comment by reiterl** [comment]
Update the is present in the edit view.
Merged main into this branch to solve conflicts.

**Review by emanuelschuetze — APPROVED** [review]

**Review by rrenkert — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Pull request merged**
