### PR TITLE
Bugfix: line number inconsistency when creating change recommendations

### PR DESCRIPTION
**Pull request by CatoTH**

### CODE REVIEW

**Comment by GabrielInTheWorld** [comment]
@emanuelschuetze Please test.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
There is still an error:
* create new motion with 5 lines
* set start line to "10"
* create a change recommendation for first line (line 10).
=> `Error: Inconsistency or invalid call of this function detected (to)`

**Comment by GabrielInTheWorld** [comment]
> There is still an error:
> 
> * create new motion with 5 lines
> * set start line to "10"
> * create a change recommendation for first line (line 10).
>   => `Error: Inconsistency or invalid call of this function detected (to)`

Please try again.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Create new change recommendation works now. 
But next error if you try to create a single pdf of an motion with change recommandation:
`Error: Inconsistency or invalid call of this function detected (to)`

**Comment by GabrielInTheWorld** [comment]
@emanuelschuetze: Ping.

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
