### PR TITLE
Fix of the datepicker reopen problem

### LINKED ISSUE #3705: Fix date picker in meeting create/update
**Current behaviour:**
If you edit or create a meeting and change the datepicker, the datepicker can open itself again 

**Reproduction:**
Tested in Chromium (Version 125.0.6422.76 (Official Build) built on Debian 12.5, running on Debian 12.5 (64-bit) )
1. Navigate to committee detail
2. create a new meeting 
3. open the datepicker
4. press cancel 
5. click on a different tab (push the current tab out of focus)
6. open the tab where you create a meeting again
7. the datepicker is open again

**Wanted behaviour:**
If the date  picker window was closed (via one of the three buttons or via clicking out of bound for the dialog) then the dialog should stay closed until the meeting date input is actively clicked again

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #3705 

When testing this issue, please make sure date picker and date range picker still function alright as this pr removes
a open picker on focus. Perhaps this part of code needs to be rebuild only in the datepicker.

### CODE REVIEW

**Review by Elblinator — APPROVED** [review]
seems to work

**Review by bastianjoel — APPROVED** [review]

**Comment by bastianjoel** [comment]
You should test if the datepicker still opens when navigating via tab press to the field.

**Review by Elblinator — CHANGES_REQUESTED** [review]
Before this Pr it was possible to open the date-picker is it is in focus and you press enter 
This is now not possible anymore. 
Please make that possible again

**Comment by reiterl** [comment]
Just tested it. @Elblinator I cannot reproduce your problem with pressing return.
Before: you need focus on the dialog icon and press return/enter to open it.
After my change: you need focus on the dialog icon and press return/enter to open it.
So here is no problem. Please give an "exact" error description.

**Comment by Elblinator** [comment]
> you need focus on the dialog icon 

wanted behaviour: you need to focus on the input OR the icon field to open the dialog

This was the behaviour before and should stay like that (Repo: focus the Event location and press tap to navigate to the date-input field

**Comment by reiterl** [comment]
Worked on the (base) date picker/date range picker. I added a check to open the picker, if pressed Return or Enter.

**Review by Elblinator — APPROVED** [review]

**Comment by bastianjoel** [comment]
I did not review this. 

@reiterl please rerequest a review if you do fundamental changes to your PR.

**Pull request merged**
