### PR TITLE
Fix projector preview

### LINKED ISSUE #2702: Fix projector preview
**Current behaviour:**
The content which is projected is not visible in the preview of the projector

**Reproduction:**
1. project something onto the projector 
2. open the "edit projector" dialog
3. content is not displayed in the preview

**Wanted behaviour:**
The content should be displayed in the preview

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2702

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
the projection is too far up if "show header and footer" is activated

**Comment by luisa-beerboom** [comment]
> the projection is too far up if "show header and footer" is activated

Two things:
1. I can't see/replicate this, so I would probably need a better replication description or a picture or something
2. All I did was fix the projection data in order to make the preview work again, I did not change anything about the preview projector itself, which is the same component as the normal projector. Unless this "projection being too far up"-thing happens _only_ in the preview and _not_ in the normal projector, I'd say that is a separate bug.

@Elblinator  Please take a closer look at this and act accordingly

**Comment by Elblinator** [comment]
This indeed only happens in the preview: 

the actual projector(same in projector-detail):
projector

projector preview:
projector_preview

projector preview without the header:
projector_preview_without

It happens with an election, a topic, the agenda, a LoS

**Additionally** png files in the preview are only a black field

**Comment by Elblinator** [comment]
the files still don't work

**Review by Elblinator — APPROVED** [review]
function

**Review by bastianjoel — APPROVED** [review]

**Pull request merged**
