### PR TITLE
Remove translation of user-filled data

### LINKED ISSUE #2007: Remove translation of user-filled data
Things like group names, workflow names etc. will be translated in the backend with https://github.com/OpenSlides/openslides-backend/pull/1502, so they should no longer be translated in the client. The (possibly non-exhausting) list of places that need to be changed:
- all places where one of the following is displayed to the user:
  - group names
  - workflow names
  - workflow state names & recommendation labels
  - countdown names
  - projector names
  - values of meeting & organization settings (since the default values are sometimes translated)
- Places where the user needs to enter a group name have a hint that the group name must be the english one - this can be removed (I think it's only the "Add to meeting" wizard, but there may be more)

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2007 

List from issue:
- [x] `{meeting|organization}.name` and the `installationNotice` in `login-mask.component.html`
- [x] `organization.description` in `dashboard.component.html`
- [x] `meeting.welcome_{title|text}` in `start.component.html`
- [x] `preamble` in `motion-slide.component.html`, `motion-content.component.html`, `motion-detail-diff.component.html` and `motion-pdf.service.ts`
- [x] `recommendation_label` in `motion-list-info-dialog.component.html`
- [x] `motions_export_title` in `motion-pdf-export.service.ts`
- [x] `title` in `createTitle` in `pdf-document.service.ts`
- [x] `users_pdf_welcome{title|text}` in `participant-pdf.service.ts`
- [x] all translations in `meeting-settings-group-detail-field.component.ts`

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]
Looks good, not tested

**Review by jsangmeister — CHANGES_REQUESTED** [review]
Just noticed: gender is also translated. This also has to be removed, especially from the import.

**Review by m-schieder — APPROVED** [review]
I have tested it in production setup with [Translate created objects at meeting.create](https://github.com/OpenSlides/openslides-backend/pull/1502) and [au-backend-translation](https://github.com/bastianjoel/openslides-autoupdate-service/commits/backend-translation).

**Comment by bastianjoel** [comment]
Although no merge conflicts are display this PR needs adjustments to work properly with current main

**Comment by jsangmeister** [comment]
@bastianjoel what changes are needed? Can you implement them? I added a few changes needed for https://github.com/OpenSlides/OpenSlides/pull/6571 and from my side, this is now done.

**Comment by bastianjoel** [comment]
I will implement them

**Comment by bastianjoel** [comment]
@jsangmeister The required changes are done now.

**Review by jsangmeister — APPROVED** [review]

**Review by rrenkert — CHANGES_REQUESTED** [review]
Creating a meeting does not work when changing language to "de". Error: data.language must be string

As far as I can see, the client sends ```language:null``` in the data object of meeting.create action.

**Comment by bastianjoel** [comment]
I am getting the error `data must not contain {'language'} properties` when creating a meeting even though the property is set. 

@jsangmeister could you have a look on that?

**Comment by jsangmeister** [comment]
@bastianjoel what's the status here?

**Comment by bastianjoel** [comment]
I cannot replicate the issue mentioned by @rrenkert.

**Comment by rrenkert** [comment]
> @rrenkert maybe you forgot to check out the client branch and only checked out the backend?

No, my backend is on OpenSlides/openslides-backend#1502 but i think my autoupdate service does not know the organization/1/default_language field. Will run 'go generate' and see.

**Review by rrenkert — APPROVED** [review]

**Pull request merged**
