### PR TITLE
fix disappearing lines due to new amendment

### LINKED ISSUE #1379: Lines disappear due to new amendment
When creating an amendment, lines in the motion disappear. 

Reproduction: 

1. create motion.
2. create an amendment in the last text area. Create new line with Enter and enter text.
Open the motion. Display diff version. --> Line disappeared.

What should happen: Adding a new amendment should not have the effect that lines in the original motion disappear in diff version.

Example: https://testintern.openslides.com/2/motions/62

Screenshot_20220718_113436

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1379

### CODE REVIEW

**Comment by bastianjoel** [comment]
https://github.com/OpenSlides/openslides-client/pull/1468/files#diff-1a091af9d93f66a9a7d0ae4e0f8a69efcfac25810d5ae0db456e1433f12efc93L117
"0" was not valid here as the value is later used as a parameter for this.diff.extractMotionLineRange which passes it to [extractRangeByLineNumbers in client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts](https://github.com/OpenSlides/openslides-client/blob/main/client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts#L1257) which expects null if the change goes till the end of the text.

**Comment by bastianjoel** [comment]
This should not be merged until #1382 is fixed.

**Comment by emanuelschuetze** [comment]
> This should not be merged until #1382 is fixed.

@bastianjoel Do you mean PR#1521?

**Comment by bastianjoel** [comment]
> > This should not be merged until #1382 is fixed.
> 
> @bastianjoel Do you mean PR#1521?

No, PR #1496 resolves #1382

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
