### PR TITLE
Add free text submitter field

### PR DESCRIPTION
**Pull request by jsangmeister**
resolves https://github.com/OpenSlides/openslides-client/issues/3362

needs https://github.com/OpenSlides/openslides-autoupdate-service/pull/864 and https://github.com/OpenSlides/openslides-backend/pull/2258

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
The additional Submitter is not exported in the pdf

motion-list: 
- additional submitter is not displayed in the motion-list view
- If you search in the  motion-list for an additional submitter, you need to find the motion with the submitter
- the additional submitter needs to be sorted in the same manner as the other submitters

The submitter also needs to be searchable via global search

If the submitters are projected there is one too many spaces

Change 'additional submitter(s)' string to 'Extension'

**Comment by jsangmeister** [comment]
- [x] added to CSV and PDF export
- [x] added to motion list view
- [x] added to filterable properties in the list view
- [x] added to `search.yml` for global search, see https://github.com/OpenSlides/openslides-meta/pull/38
  - Note: I did not create a PR for this as the search service will get updated automatically after the meta PR is merged
- [x] changed input label to "Extension"

> * the additional submitter needs to be sorted in the same manner as the other submitters

What do you mean by that? I currently simply append it to the normal submitters.

> If the submitters are projected there is one too many spaces

Cannot reproduce.

**Comment by jsangmeister** [comment]
Included the new submitter field when sorting the motion list by submitter.

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
if a motion has only an extension as a submitter then the extension string is not displayed in the motion-list view

**Comment by Elblinator** [comment]
>>  the additional submitter needs to be sorted in the same manner as the other submitters

> What do you mean by that? I currently simply append it to the normal submitters.

already fixed that part

>> If the submitters are projected there is one too many spaces

> Cannot reproduce.

Ignore that part, there might have been a loading bug, cannot reproduce anymore

**Review by Elblinator — APPROVED** [review]
function

**Pull request merged**
