### PR TITLE
Anonymous user

### PR DESCRIPTION
**Pull request by bastianjoel**
part of #3955

~~this PR assumes that `active_meeting_ids` in organization gets restriction mode `A`.~~ (changed)

Needs:
https://github.com/OpenSlides/openslides-media-service/tree/feature/anonymous-user

### CODE REVIEW

**Review by MSoeb — CHANGES_REQUESTED** [review]
- [x] Login page: Rewording of new button to 'Public access'
- [ ] ~~User account name for Anonymous user: Rename it to 'Public'~~
- [ ] Group permission matrix > Group default name for anonymous user: rename it to 'Public'
- [ ] Group permission matrix > Positioning: The group should always be listed as the first group on the left after activation.

Settings > General: 
- [ ] Add a new heading 'System' above 'Closed Meeting'. The formatting should be the same as for 'Meeting information'
- [ ] Place new setting below 'closed meeting'
- [ ] Add a gray placeholder help text under new setting (Hint: will be changed during translations)

- [x] Global search: Didn't work currently. It should be possible to use Global search as public user. The accessible content is limited and defined by all public available data.
- [ ] Dashboard > calender: Üublic user could see committee icon. -> Should not be visible
- [ ] Chat / commentary field for motions: Public user group can't be selected. -> It should be possible to set the public group as 'Group with reading permission'. / In comparison: Writing should not be possible. (needs discussion)

**Comment by bastianjoel** [comment]
> Group permission matrix > Group default name for anonymous user: rename it to 'Public'
Needs to be done in backend

> Group permission matrix > Positioning: The group should always be listed as the first group on the left after activation.
I would prefer an backend solution here too

> Global search
Works for me might be a problem with your setup

**Comment by bastianjoel** [comment]
> Add a gray placeholder help text under new setting (Hint: will be changed during translations)
Why not just add it when translating?

**Comment by rrenkert** [comment]
> > Global search
> 
> Works for me might be a problem with your setup

Correct. Our stating setup does not have a running search service. I will talk to @m-schieder .

**Review by MSoeb — CHANGES_REQUESTED** [review]
Checked it with @emanuelschuetze. We've found the following issues:

- [ ] User profil: language change doesn't work instantly. reload is needed
- [ ] Group name: Should be changed from 'Anonymous' to 'Public'. [Backend]
- [ ] Group position after activation: 'Public' group should be first in the group listing. [Backend]
- [ ] Dashboard > calender > meeting card: old committee icon position is not clickable -> whole card shoould be clickable
- [ ]  Chat / commentary field for motions: Public user group can't be selected. -> It should be possible to set the public group as 'Group with reading permission'. - No writing permission. It should be a one-way-communication. / @rrenkert I have in mind we talked about it, but I can't remember if there were any  hurdles to implement it. If yes, could you please write them for down?
- [x] User name: Should be changed to 'Public'.

**Comment by bastianjoel** [comment]
There are some problems with the dashboard being displayed after reload even with just one meeting public.

**Comment by MSoeb** [comment]
Additional Change requests.

Group Permission table:
- [ ] As already described, changes are still missing in the group permissions table. Keywords group name and position.
- [ ]  If the setting for public user is deactivated, the group is still visible. -> Target: Group should not be visible after deactivating the setting for public user

Organization level - layout:
- [ ] add new icon to public meetings. Icon = globe
- [ ] Visibility of icon in calendar: place icon the left side of the committee icon. Important: Public users should NOT see this icon
- [ ] Visibility of icon in meeting list: place icon left to meeting title (like closed meeting icon).
- [ ] Visibility of icon in committee detail view: place symbol left to meeting title.

New filter in meeting list:
- [ ] Add a new filter 'Status' in meeting list. The options should be 'is archived', 'is not archived', 'closed' and 'public'.

Scenario: logged in as public user
- [ ] User profile: Change name to 'Public Access'. This should also be changed in the user profile if it is open, left to the light/dark mode button.
- [ ] User profile: letters with dots are not fully visible. (example: Ö dots)
- [ ] User profile: Imprint can't be opened
- [ ] Global search: didn't work currently -> global search in available content should be possible
- [ ] User is in meeting in the Elections menu and the right to view elections is revoked. An error message appears stating that the user should not be there. Clicking on the button takes you to the dashboard. -> Open question: How can we improve this? It is simply a strange behavior when a user is torn out of the meeting and has to open it again manually. 

Meeting - archived and public:
- [ ] Open question: Currently you can mark a meeting as archived and public. However, this means that the meeting is not publicly accessible. -> Is it possible and (technically) sensible for us to make a meeting archived and publicly accessible?

**Comment by bastianjoel** [comment]
> As already described, changes are still missing in the group permissions table. Keywords group name and position.

Please open a backend issue for that. This will not be done here.

**Comment by bastianjoel** [comment]
> Global search: didn't work currently -> global search in available content should be possible

This is still not an issue with this PR but with the setup.

**Comment by MSoeb** [comment]
> Please open a backend issue for that. This will not be done here.

For documentation: https://github.com/OpenSlides/openslides-backend/issues/2641

**Comment by bastianjoel** [comment]
> User is in meeting in the Elections menu and the right to view elections is revoked

This is also not specific to anonymous user. I would prefer fixing this separately.

**Review by MSoeb — CHANGES_REQUESTED** [review]
- [x] Visibility of icon in calendar: place icon the left side of the committee icon. Important: Public users should NOT see this icon --> Globe is currently visible in Public Access. Globe should not be visible. Also the position of the icon is wrong. The globe should be placed to left side of the committee icon, not left to the meeting name. 
- [x] Globe needs tool tip 'public'
- [ ] Add a new filter 'Status' in meeting list. The options should be 'is archived', 'is not archived', 'closed' and 'public'. -> The new filter that summarizes the different statuses of meetings is still missing. The 'Archived' filter is then obsolete as these options are integrated in the new 'Status' filter and can be deleted. 
- [x] Global search: didn't work currently -> global search in available content should be possible -> didn't work. I get error messages in console by searching something. (TypeError: Cannot read properties of null (reading 'message'))

**Comment by bastianjoel** [comment]
> Global search: didn't work currently -> global search in available content should be possible -> didn't work. I get error messages in console by searching something. (TypeError: Cannot read properties of null (reading 'message'))

Still a setup issue. You don't need to document this here.

**Comment by bastianjoel** [comment]
> Add a new filter 'Status' in meeting list. The options should be 'is archived', 'is not archived', 'closed' and 'public'. -> The new filter that summarizes the different statuses of meetings is still missing. The 'Archived' filter is then obsolete as these options are integrated in the new 'Status' filter and can be deleted.

A second filter will be used. Option `is closed` needs to be renamed to `is not public`

**Comment by MSoeb** [comment]
Have tested now the global search. Changes needed:

- [ ] The gray description path in a search result has html code in it. -> description should be clean without the code.
image

- [ ] I could search for users like Administrator and I get a result which refers to the account menu. Also the option to search in participants is available. This should not happen. The public access is only for content, not accounts or users. .  
--> solution: Participant filter should not be available. Searching for users should not list results associated to the account menu or any participant menu.

**Review by MSoeb — DISMISSED** [review]
See previous comment

**Comment by bastianjoel** [comment]
> The gray description path in a search result has html code in it. -> description should be clean without the code.

I suspect this also happens for normal users. Please open an separate issue.

**Comment by bastianjoel** [comment]
> Participant filter should not be available. Searching for users should not list results associated to the account menu or any participant menu.

This is also not related to this PR. Please contact me if you want further explanation.

**Comment by rrenkert** [comment]
> > Participant filter should not be available. Searching for users should not list results associated to the account menu or any participant menu.
> 
> This is also not related to this PR. Please contact me if you want further explanation.

@bastianjoel Can you please create a new issue for this to address the problem correctly?

**Comment by Elblinator** [comment]
https://github.com/OpenSlides/openslides-client/issues/4197

**Review by emanuelschuetze — APPROVED** [review]

**Review by luisa-beerboom — APPROVED** [review]

**Pull request merged**
