### PR TITLE
Rename fields

### PR DESCRIPTION
**Pull request by jsangmeister**
Implement changes needed for https://github.com/OpenSlides/openslides-backend/pull/1653

### CODE REVIEW

**Comment by r-peschke** [comment]
Backend PR https://github.com/OpenSlides/openslides-backend/pull/1653 ready to merge, but waiting for this one

**Comment by jsangmeister** [comment]
@bastianjoel the integration tests are failing, even after restarting. Do I need to change anything there? A simple search did not turn up any relevant places.

**Comment by bastianjoel** [comment]
You need to merge current main

**Comment by jsangmeister** [comment]
thanks!

**Review by rrenkert — APPROVED** [review]

**Pull request merged**
