### PR TITLE
Small improvement to the get-forwarding-meetings presenter call

### PR DESCRIPTION
**Pull request by reiterl**
Update the get-forwarding-meetings call to be more safe.

Part of #3067

### CODE REVIEW

**Comment by bastianjoel** [comment]
Why has this the `needs investigation` tag?

**Comment by reiterl** [comment]
The issue has "needs investigation", so I used it here too.

**Review by Elblinator — APPROVED** [review]
I tested the forwarding a bit 
It is possible that this solution only fixes part of the problem due to the unknnown circumstances of this bug

But everything worked right now

**Review by bastianjoel — CHANGES_REQUESTED** [review]
I am not sure if this is the solution we want here. Your fix is just suppressing the error. 

I guess the problem here is `forwardingMeetingsAvailable` which is called within constructors of other components and could therefore be called before a meeting id is available. If this is the case this could result in the forwarding button not being displayed. 

To make this more safe I would suggest waiting for a meeting id to be available. The `ActiveMeetingIdService` contains `undefined` in its meeting id observable as long as it is not initialized which you could use to differentiate between "not in a meeting" and "meeting not loaded".

**Comment by reiterl** [comment]
Mmh, I need to think about this issue, when I have more time.

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — APPROVED** [review]

**Pull request merged**
