### PR TITLE
Fix blank screen on projection switch

### LINKED ISSUE #2922: Prevent white projector when motion switch
**Current behaviour:**
If one motion is projected and then another motion is projected there is a 1-2 sec delay where the projector has no text but white space 

**Reproduction:**
in a meeting:
1. create two motions with different titles and texts
2. project one of the motions 
3. open the projector-list
4. now project the other motion
5. there should be a short moment where the projector is completely white

**Wanted behaviour:**
The time to switch the motions should be reduced

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2922 

With this PR before a new projection is displayed it will be waited until all current projections loaded their content.

### CODE REVIEW

**Comment by bastianjoel** [comment]
Should now also improve the situation with #2066

**Comment by emanuelschuetze** [comment]
@rrenkert needs performance tests with 1000+ users

**Comment by bastianjoel** [comment]
I don't think this necessarily needs performance tests. The issue was reproducible even without any load for motions.

**Review by rrenkert — APPROVED** [review]
Did the performance tests. Works great.

**Pull request merged**
