### PR TITLE
Make meeting settings date range input send updates

### LINKED ISSUE #2596: Can't set meeting dates in general settings
**Description**
The meeting start and end date can not be modified via the general settings of a meeting. Clearing the dates works as expected.
A workaround is to set the start and end date via other forms like committee->threedotmenu of meeting->edit.

**Reproduction**
* Navigate to Meeting->Settings->General
* Edit the start and end date
* Save
* Navigate to some other page
* Navigate back to Meeting->Settings->General
-> The date values are still on the previous values.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2596 

TODO:
- [ ] There are updates now, but for some reason only for the end date, as the daterangepicker component seems to only send the original start date, idk why => Fix that

### CODE REVIEW

**Comment by bastianjoel** [comment]
Cannot replicate the issue with your PR.

**Comment by luisa-beerboom** [comment]
> Cannot replicate the issue with your PR.

1. Create meeting ranging from 1.8.2023 to 30.8.2023
2. Go to meeting settings and change date range to 2.8.2023 - 31.8.2023
3. Reload
4. The daterange picker will show the daterange 1.8.2023 - 31.8.2023

**Comment by bastianjoel** [comment]
I still cannot replicate this.

**Comment by bastianjoel** [comment]
Selection works now but somehow the clearing of the form won't be displayed in the ui.

**Pull request closed without merging**
