### PR TITLE
Add committee selector to motion meta data submitters

### LINKED ISSUE #3429: Free Text submitter: committee selection
Description: The new feature free text submitter (solved in #3362) needs an enhancement for committes. The aim is to add a committee selection field under the new free text field.

- Data base: The data of the selection field is based on the committees that can forward a motion to the meeting and NOT committees, that can receive a motion from this meeting. So the data base is the counter part to motion forwarding.
- Layout: The selection field should follow the layout of other committee selection fields like for example the one for recommendation extensions. (see example bellow)

image

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #3429 

This selector allows to fill the submitters extension text field with committee names. Select a committee and press save, the committee name is appended to the extension text field.

The received forwarding committees are returned by the presenter, which fills the possible committee names.

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
If you select one committee please add it immediately onto the Extension and -if the extension field is not empty- separate committee names with a middot
If you need the an example of the wanted (in the Issue referenced) behaviour look at the extension from recommendations

**Comment by reiterl** [comment]
Where can I find the extension of recommendation? @Elblinator please give a step-by-step instruction to find that widget.

**Comment by reiterl** [comment]
Updated the committee field to include:

- direct fill
- middot
- keepOpen
- disableIds.

This is more in the way the `motion-extension-field` is built.

**Comment by reiterl** [comment]
Please review again.

**Review by Elblinator — APPROVED** [review]
LGTM :)

**Review by bastianjoel — APPROVED** [review]

**Pull request merged**
