### PR TITLE
Adjust projected motion/topic/election to new detail view

### LINKED ISSUE #2729: Adjust projector view to new detail-view
The detail views from Motion, Election and Agenda got changed (#2728) when they are now projected the projection needs to adjust accordingly:

**Description from the other Issue:**
What was changed:
- every title should stay how they are (relevant for Motion, Agenda and Election)
- H1 should not have primary or accent colours, but should be black/greyish like the rest of the text (UPDATE: font-weight: 400)
- H2 should have font-weight: ??? -> was marked as fine in last discussion; Open new issue please.
- H3 should have font-weight: 600
- H4 should have font-weight: 600 and font size: 1 em
- H5 should be kursive and have font-size: 1 em
- H6 should not be kursive or bold, and font-size: 1 em

waiting for https://github.com/OpenSlides/openslides-client/issues/2728

UPDATE 2024-07-18 (ES):
Needs discussion with @Eich-hoernchen

### LINKED ISSUE #3992: Change Appearance of several detail-views part 2
**Wanted behavior**
Some detail views were changed by https://github.com/OpenSlides/openslides-client/issues/2728 
is was now decided thatthe fon-weight from H2 should be changed 700 (see https://github.com/OpenSlides/openslides-client/pull/3693#pullrequestreview-2229606093)

### PR DESCRIPTION
**Pull request by Elblinator**
closes #2729 
closes #3992

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
needs rebase for final test

**Review by Eich-hoernchen — APPROVED** [review]
perfect

**Review by bastianjoel — APPROVED** [review]

**Review by MSoeb — CHANGES_REQUESTED** [review]
A) PR didn't work. New motions can't be created. The action is interrupted with a error in snackbar and console. Therefor it's not possible to test

errors:
image

image


Repro:
1. open a meeting
2. open motions
3. create a new motion. try to save it. 


B) Please edit the font style of H2 heading. Font weight should be 700 in the projector to fit the font size in the motion. Even if it wasn't part of the original issue, we should change this so that the appearance between motion and projection is identical.

**Review by MSoeb — CHANGES_REQUESTED** [review]
Tried to create a new motion, but it doesn't work. Saving is not possible. A snackbar and a console error appears.

Snackbar error: Ein unbekannter Fehler ist aufgetreten.

Console error:
image

**Review by MSoeb — APPROVED** [review]
Looks overall fine.

Note: During testing I've got two error messages by reloading the instance login page.
1. By opening the instance for the first time, I got a snackbar error with 'Fehler: Presenter server_time does not exist.'
2. Additionally an error appears in the console which appears again by reloading the login page. Error message: Error: Operator has not fully loaded yet.

I've spoken with @m-schieder and @Elblinator about them. Both errors can't be reproduced by them. Also errors should not appear after merging. It seems to a something related to test instance.

**Pull request merged**
