### PR TITLE
Prefix can be empty

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Please check, that the ui (creating, updating, ...) accepts an empty prefix

**Comment by FinnStutzenstein** [comment]
I gues we have to wait for the backend to implement the changes, right?

**Comment by GabrielInTheWorld** [comment]
> Please check, that the ui (creating, updating, ...) accepts an empty prefix

The UI already accepts an empty prefix. The UI was not adjusted so, that it doesn't accept an empty prefix.

**Comment by GabrielInTheWorld** [comment]
> I gues we have to wait for the backend to implement the changes, right?

I think so, too.

**Comment by FinnStutzenstein** [comment]
Waiting for https://github.com/OpenSlides/openslides-backend/issues/395

**Pull request merged**
