### PR TITLE
Motion with amendments add icon and amendment number

### PR DESCRIPTION
**Pull request by Elblinator**
closes part of #4159 

>- the same warn icon should be projected as it is in the motion-detail
>- The amendment nr should be projected in the same line as the icon (if there is no nr then only the icon is projected
>- The amendment status should not be projected
>- The icon and Nr should be indented in the same way as they are displayed in the motion-detail
>- If an amendment has no icon and no Nr then the word "Amendment" should be projected 
>- If reasonably possible in this issue the submitter from the amendment should be behind the Nr

The first part is not part of an enhancement but a bug in the motion projection

### CODE REVIEW

**Comment by Elblinator** [comment]
Notes: 
bottom:12px is okay if the first line of a paragraph is changed

bottom needs to be bigger if a line inside of a paragraph is changed

**Review by bastianjoel — APPROVED** [review]

**Review by bspekker — CHANGES_REQUESTED** [review]
Two superfluous line numbers in projector: 
1. Additional line number with empty line appears for first amendment if first amendment only changes up to line x in the motion and second amendment makes changes from line x+1 onwards.
image

2. Line number overlaps with conflict symbol if one amendment spans several paragraphs but the other one does not with the conflict only appearing in the second paragraph.
image

**Comment by Elblinator** [comment]
I removed the doubled line numbers

**Review by bspekker — CHANGES_REQUESTED** [review]
Amendment numbers on projector use different font for italics than in the motion. This causes the colon to not be highlighted in gray completely.

Indication of change recommendations are missing. Sould say "Change recommendation" like it does for amendments without number and symbol.

**Review by bspekker — APPROVED** [review]

**Pull request merged**
