### PR TITLE
Fix perm check for los content addSelf method

### LINKED ISSUE #4402: List of speakers: 'add me'/point of order Button is visible, even if user doesn't have permission
**Describe the bug**
The 'Add me' and the point of order button in the list of speakers is always visible, even though users do not have permission to add themselves to the list of speakers. This leads to the error message 'Error: You are not allowed to perform action speaker.create. Missing Permission: list_of_speakers.can_be_speaker'. 

**How to Reproduce**
1. open a meeting
2. open agenda > create an item
3. open participants > create a user A as delegate with the permission to see the list of speakers
4. project the agenda item
5. login as user A, open the Autopilot > you will see the 'add me' button and you can click it > error appears

**Expected behavior**
If users ONLY have the permission to see the list of speakers, the 'Add me' and point of order button should NOT be visible. 

Only with the permission 'Can put oneself on the list of speakers' can users see these buttons and put themselves on the list of speakers.

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #4402

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

**Review by Elblinator — CHANGES_REQUESTED** [review]
If a user is already on the LoS then they are allowed to remove themselves, hence the buttons to remove oneself should be visible

**Comment by reiterl** [comment]
@Elblinator your comment is not about this issue, please open a new issue for the remove button stuff.

**Comment by reiterl** [comment]
@rrenkert  Please look at this issue, QA is changing the scope of an issue, please also check the code.

**Comment by rrenkert** [comment]
@reiterl Did you change the code?

**Comment by Elblinator** [comment]
The Issue you are fixing states that the "Add me" Button and the PoO button should only be visible if a user is allowed to do so. 
The backend allows a user to remove themselves even if they are not allowed to add themselves onto a LoS. 
With your PR in it's current state the backend and the client will divert from each other. That was not wanted.
The Issue is not complaining about the "Remove me" button on a LoS. That button was not a part of this issue

**Comment by reiterl** [comment]
I see the point.

**Comment by reiterl** [comment]
I have added another commit, allowing an operator to remove themself as speaker or POI.

**Review by Elblinator — APPROVED** [review]
function and code review from last commit

**Pull request merged**
