### PR TITLE
Fix style of the home page

### LINKED ISSUE #3752: UI issue: wrong heading style on Home page
**Description:** The heading styling on the Home page has changed. It has the wrong color. Maybe other styling parts affected, but i'm not sure. Please check it. - I guess this happend by changing the headings in #2728 

**Old Style:**
image

**New wrong style:**
image

**What should happen:**
Heading should have the old Styling.

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #3752

### CODE REVIEW

**Review by Elblinator — APPROVED** [review]
function

**Review by bastianjoel — CHANGES_REQUESTED** [review]
I would prefer a solution without ng-deep. 

Maybe create a new component for user html content and set the components `encapsulation` to `None`.

**Comment by reiterl** [comment]
If we would use an encapsulation of none in the user component, it styles would be used app wide. That is a problem.
encapsulation doesn't have an option for use styles for comp and sub comps.

**Comment by bastianjoel** [comment]
You could use an unique class name then? 
Maybe just change the name `underlined-links` to something else for now.

**Comment by reiterl** [comment]
Renamed 'underlined-links' into 'detail-view' as the class provides the 'detail-view-appearence'.

**Pull request merged**
