### PR TITLE
Hide statute amendments checkbox

### PR DESCRIPTION
**Pull request by Elblinator**
first step of #3085

### CODE REVIEW

**Review by emanuelschuetze — COMMENTED** [review]
It it really the right way to hide a settings option? In earlier versions we used a single line "hide" attribute for settings. Maybe we can support this?

**Comment by Elblinator** [comment]
If I understand the Code correctly this option cannot simply be called but needs new implementing. 
Given that we do not plan to hide settings in general, but just for the moment, I would prefer this temporary workaround

But I could misunderstand the code. @bastianjoel what do you think about this?

**Comment by jsangmeister** [comment]
Why not simply remove the setting from the definition list? Seems cleaner than implementing this workaround.  @emanuelschuetze the `hide` attribute was probably in OS3 - in OS4, this does not exist (yet).

**Comment by Elblinator** [comment]
> Why not simply remove the setting from the definition list?

Removing it in the definition-list makes it completely unusable. Other files need the definition to determine whether or not statutes are allowed

**Comment by jsangmeister** [comment]
I meant from the `meeting-settings-definition.ts`. That only defines what is displayed where in which group and not which settings are generally available.

**Comment by jsangmeister** [comment]
The previous suggestion did not work since the `MeetingSettingsDefinitionService` parses the definition list to determine which fields to request, which I did not know. I implemented a more general solution instead which can hide arbitrary entries, like @emanuelschuetze suggested. @Elblinator please review.

**Comment by Elblinator** [comment]
Looks very nice and clean :)

**Review by emanuelschuetze — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]

**Pull request merged**
