### PR TITLE
Use OpenSlides specific styles for HtmlToPdfServices

### LINKED ISSUE #2118: issue with headings (pdf export and OpenSlides formatting doesn't match)
**Description:** The formatting of headings is not identical in OpenSlides and in exported PDF documents. 

**Openslides formatting:**
Screenshot_20230323_130928

**PDF export formatting:**
Screenshot_20230323_131532

**Reproduction:**
1. create a motion
2. add headings in motion text or reason field
3. create pdf export and compare the formatting

**What should happen:**
The formatting should be identical between OpenSlides text edit and pdf export. 

Update 28.10.2024: Please take care of the comment, what has changed with the new editor.

Here the  the H# context: 
https://github.com/OpenSlides/openslides-client/issues/2728

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2118 

Created pdfMake styles that as best as possible approach the OpenSlides header styles

### CODE REVIEW

**Comment by luisa-beerboom** [comment]
> Can #2271 be integrated into this PR?

Certainly it could, but I would prefer to keep this PR limited to the topic of fixing/changing pdf styling.

**Comment by luisa-beerboom** [comment]
@Eich-hoernchen @MSoeb This may change the styles in pretty much all pdf exports, please check if this outcome is desirable from a design perspective

**Comment by Elblinator** [comment]
for example pdfs, see https://testintern.staging.openslides.com/150/mediafiles/228

**Comment by Elblinator** [comment]
waiting for #2728

**Comment by Elblinator** [comment]
the issue from this PR should be fixed after the other issues from the display are implemented 
When that happened a new more up-to-date PR should be created

**Pull request closed without merging**
