### PR TITLE
Add invite-to-call to LOS

### PR DESCRIPTION
**Pull request by tsiegleauq**
Adds functions to invite and kick users to a jitsi call via LOS

### CODE REVIEW

**Comment by tsiegleauq** [comment]
following issue needs to be solved:
https://github.com/OpenSlides/openslides-icc-service/issues/30

following PR has to be merged:
https://github.com/OpenSlides/OpenSlides/pull/6305

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Tested.
* Admin A who invites user B gets also the invite dialog.
* user B gets in every tab the invite dialog. After accept this all dialogs in other tabs should closed.

**Comment by tsiegleauq** [comment]
> Admin A who invites user B gets also the invite dialog.

Fixed it. Apparently the sender of ICC messages will always receive a copy of their own messages.

> user B gets in every tab the invite dialog. After accept this all dialogs in other tabs should closed.

This might not be easy atm. indexedDB cannot detect changes on another tab, see
https://github.com/cyrilletuzi/angular-async-local-storage/issues/386

There is this browser API ( https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API ), but it seems to fairly new ( https://caniuse.com/?search=Broadcast )

I'll have a look at it.

**Comment by tsiegleauq** [comment]
Now with broadcast.service.ts for real time inter-tab-communication

**Review by GabrielInTheWorld — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
