### PR TITLE
Restyled account list and reworked account search

### LINKED ISSUE #1575: Extend search and visible fields in account list
Additional fields below the name (see meeting meta info in calendar for style):
- email
- username

Visible fields behind the name:
- Status (no natural person(committee icon); inactive)

New column for other meta info:
- number of committees
- last email

Additional fields used when searching in the account list:
- email
- username

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1575

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]
not tested

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Account list needs rework:
* gets vertical scroll bar if account has email address and username
* use full name in bold (as committee title in committee list view) maybe bigger font size 
* show mail/username like this: "<email> · <username>" (without label "E-Mail"/"Username")
* move icon column to right side
* remove committee icon, meeting icon is enough

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
* ellipse with "..." required if name line is to long
* the inactiv/committee icons should placed on first (name) line which required a smaller icon size (try to use a very long name with inactiv icon: icon is not visible)
* hover is very difficult if you start by hovering meeting icon and than try to get tooltip for the mail sent icon -> not possible. You have to hover from bottom to top...

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Please order the committes by name (currently it looks like by id which is not helpful)

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
