### PR TITLE
Hide inactive SLLOS

### PR DESCRIPTION
**Pull request by jsangmeister**

### CODE REVIEW

**Comment by jsangmeister** [comment]
Linter complains about the "nested subscribes" antipattern. @bastianjoel will have a look. The code should work, however, if you want to have a look @MSoeb.

**Comment by jsangmeister** [comment]
The projector code is done separately in https://github.com/OpenSlides/openslides-autoupdate-service/pull/829, without it, the projector slides will still display inactive structure levels.

**Review by jsangmeister — COMMENTED** [review]
Approved

**Comment by jsangmeister** [comment]
@bastianjoel introduced a regression with his changes: Clearing the structure level/a user no longer hides the timer. He will have a look.

**Review by rrenkert — APPROVED** [review]

**Pull request merged**
