### PR TITLE
Map the ids of every displayable model to its specified `sequential_number` (#733)

### LINKED ISSUE #733: Request a model (with a detail-view) depending on its sequential number and a meeting's id
This can be accomplished maybe by doing these steps:

1. When in a meeting: Request all displayable models (displayable: with a detail-view) and their sequential numbers
2. List them in a dictionary like "{ [collection: string]: { [ <meeting_id/model.sequential_number> ]: model/id } }"
3. When navigating to a detail-view, we can easily get the id of a model by checking this dictionary
4. A further benefit of this approach would be, that if <meeting_id/model.sequential_number> returns `undefined`, the requested model does not exist.

It has to be waited for OpenSlides/openslides-backend#1130, since only motions have a sequential number at the moment.

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #733

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
error after creating a new motion in a new meeting (there are some other meetings with motions):
`The requested path contains undefined segment at index 2`

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to create a new amendment for a motion (here: motion/1):
  
`Error: The following models do not belong to meeting 15: ['motion/1']`

There is the wrong motion text shown in the paragraph choice list!

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to create a new topic item or assignment:
`TypeError: Cannot read properties of undefined (reading 'length')`
-> tinymce editor is not loaded correctly
(motion works)

**Comment by GabrielInTheWorld** [comment]
Waiting for OpenSlides/openslides-backend#1013.

**Review by emanuelschuetze — APPROVED** [review]
Ok. Wait for backend.

**Comment by emanuelschuetze** [comment]
Rebased

**Review by emanuelschuetze — APPROVED** [review]
Retested

**Pull request merged**
