### PR TITLE
Fixes creating of change-recommendations (#987)

### LINKED ISSUE #987: Broken start and end line numbers for change recommendation creation

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #987.

### CODE REVIEW

**Comment by jsangmeister** [comment]
Since this is in "Review in progress": All places evaluating `line_to` of change recommendations must be changed to, they assume that it is exclusive as well. Otherwise the diff view will probaby be broken.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Does not work for a single line (e.g. try to cretae a cr for line 2 -> editor is empty -> enter something -> line 2 exists 2 times...)

**Comment by GabrielInTheWorld** [comment]
@CatoTH: Currently, the linenumber algorithm expects the format [from, to) for changed linenumbers. The backend, however, detects collisions of linenumbers, if there is already one change recommendation for a linenumber, which will be changed by another change recommendation. This is especially the case, if a change recommendation should be created and regardless whether a linenumber is excluded in the linenumber algorithm. 
Therefore, we have the following options:
- Either we adjust every time we get a change recommendation or send an update/create of a change recommendation the `to` field
- Or we adjust the linenumber algorithm to handle `[from, to]`

**Comment by CatoTH** [comment]
In principle, I don't have very strong opinions about this. The reason for the implementation as it is: it actually refers to the line numbers, not the lines. That is, to change line 3, the algorithm extracts all in between line number 3 and line number 4, which is line 3. One could change this, you would just need to make sure that the "+1" is done whenever the line extraction and diff algorithms are applied.

**Comment by GabrielInTheWorld** [comment]
> One could change this, you would just need to make sure that the "+1" is done whenever the line extraction and diff algorithms are applied.

Then, could you do this please?

**Comment by jsangmeister** [comment]
> * Or we adjust the linenumber algorithm to handle `[from, to]`

This was also what I had in mind when changing the backend and what we talked about @GabrielInTheWorld - we should keep this consistent.

**Comment by GabrielInTheWorld** [comment]
> > * Or we adjust the linenumber algorithm to handle `[from, to]`
> 
> This was also what I had in mind when changing the backend and what we talked about @GabrielInTheWorld - we should keep this consistent.

Yes, this also my preferred choice.

**Comment by emanuelschuetze** [comment]
the new PR #1012 contains the commit of this PR. -> close this PR.

**Pull request closed without merging**
