### PR TITLE
Built in hidden pseudo-options to insure selector values are loaded

### LINKED ISSUE #2310: In participant edit view and the edit dialogue in the participant list, the participant search selectors for the delegations don't show the currently selected names

### PR DESCRIPTION
**Pull request by luisa-beerboom**
...in search selector

Closes #2310

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]
I don't like this but as of https://github.com/angular/components/issues/13087 it seems like there is no better way to do this.

**Review by bastianjoel — APPROVED** [review]
`>:(`

**Comment by bastianjoel** [comment]
@luisa-beerboom Can this be closed now?

**Comment by luisa-beerboom** [comment]
@bastianjoel yes, closing this now

**Pull request closed without merging**
