### PR TITLE
Improves the import of committees and other csv models

### LINKED ISSUE #579: Clean up the `BaseImportService`
The importing of models by csv files works very well (introduced lately in #525). But the `BaseImportService` has grown so much, so it has to be cleaned up.
Especially the "main" function (`doImport`) can be extracted into own files/classes.
These are other functionalities:

- Functions affected by `doImport` (like `getModelsToCreate`, `doBeforeImport`, `doAfterImport`, `doAfterImportCleanup`, `resolveEntry`)
- The properties of csv-models can be verbose and programmatically the properties can get a suffix `_id` or `_ids` (depending on if a property is multiple or not)
- `createEntries` & `sendRequest`
- Maybe a user can choose how many models will be created at once (1, 5, 10, 50, 100, all)

### LINKED ISSUE #728: Enhance the csv import of committees
There are some improvements:

- [ ] Forwardings will be created **after** the committees are created
- [ ] In the preview should be shown how many forwardings will be created after the committees has been created

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
The client calculates the number of forwardings

Fixes #728
Fixes #579

### CODE REVIEW

**Comment by alveolus** [comment]
Die Berechnung erfolgt korrekt.

Bitte zusätzlich umsetzen:
- [ ] In der Vorschau-Tabelle unterhalb des Titels stehen die Schlagwörter. Vor jedem Schlagwort sollte das Icon local_offer eingefügt werden, damit klar ist, dass es sich dabei um ein Schlagwort handelt.
- [ ] Der Text in der Zusammenfassung sollte nicht lauten "2 Forwardings will be created", sondern: "2 additional Committees will be created" 
- [ ] Neue Zeile darunter mit der Gesamtzahl der Forwardings: "XY Forwardings werden definiert"

2 zusätzliche Gremien werden erstellt, weil diese in den Weiterleitungen genannt genannt werden.

Please additionally implement:
- [ ] The preview table below the title contains the tags. In front of each tag the icon local_offer should be inserted, so that it is clear that it is a tag. 
- [ ] The text in the summary should not be "2 Forwardings will be created", but: "2 additional Committees will be created, because they are mentioned in the Forwardings"
- [ ] New line below: XY "Forwardings defined"

**Comment by GabrielInTheWorld** [comment]
@alveolus or @emanuelschuetze please test it again.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to import the committee example csv file. I get 3 errors in console:
- `Error while parsing meeting -  TypeError: this._shouldCreateModelFn is not a function`
- ` Error: Cannot find a differ supporting object '1' of type 'string'. NgFor only supports binding to Iterables such as Arrays.`
- `Error: Cannot find a differ supporting object 'Meeting B1' of type 'string'. NgFor only supports binding to Iterables such as Arrays.`

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Retested:
* Import csv example file -> works good.
* Try to import same csv file again 
-> Preview shows in red "3 entries will be ommitted." but other values seems to be imported, e.g.:
1 Committee management will be created
3 Forwardings will be defined
2 Meetings will be created

Import button is active (not disabled). If you click import a new account is created.
Expected: nothing should be imported because "3 entries will be ommitted." .

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
