### PR TITLE
New design for motion polls

### LINKED ISSUE #3816: Fix buttons for vote options in auto pilot
The buttons for motion polls in the auto pilot should have the behavior as it was before the "redesign election ballot" rework.

### LINKED ISSUE #3825: Topic Polls - small UI change
**Description:** The layout of topic polls needs a small UI improvement. The 'Yes' in the following screenshot should not be there. It's not needed for topic polls. It should be hidden or disabled. 

image

### PR DESCRIPTION
**Pull request by Elblinator**
possibility for new motion-poll design
closes #3816 
closes #3825

### CODE REVIEW

**Comment by Elblinator** [comment]
I talked with @emanuelschuetze and @MSoeb
We decided on a new wanted behaviour
- In the motion-detail-view: the (active) motion-poll should stay as it was 
- In the autopilot: the (active) motion-poll should look like an election(assignment). The "Candidate" should be the poll title and the three buttons should look like they do for the election

I'll update this PR accordingly/close it, dependent on what's easier to implement

**Review by luisa-beerboom — APPROVED** [review]

**Review by MSoeb — CHANGES_REQUESTED** [review]
Two changes needed that affect small screen sizes. (Testing with scaling on iPhone SE in autopilot):
- The space between the text 'Yes/No/Unvote' and the voting boxes becomes larger on small screens, as an additional component increases it. -> Additional component should not appear on small screen sizes. The distance should remain the same.
- A scrollbar appears when voting is active. -> Please adjust so that no scrollbar appears

**Comment by Elblinator** [comment]
I changed the appearance of the active poll

I could not reproduce the scrollbar, please check if it is still present and if it is write down the reproduction

**Review by MSoeb — APPROVED** [review]
The scrollbar doesn't appear anymore. I think the change has fixed this as well.

The distances look good now.

**Pull request merged**
