### PR TITLE
Improve additional submitters committee select

### LINKED ISSUE #3689: Motion > committee submitter field: committee submitter extension not visible
**Description:** The new submitter field “Committee” does not work properly. The selection field is not directly visible. Only superadmins can see the new field immediately. In addition, it is not possible to see the field with the group permission “Can edit metedata”.

**Reproduction:**

Step 1 -> 6 as superadmin
Step 7 -> 10 as meeting admin in another browser
Step 11 -> 13 as superadmin
Step 14 as staff user in another browser

1. create two committees (A and B)
2. set a motion forwarding from B to A
3. open meeting A
4. open motions > create a new motion. 
5. edit submitter in metadata. Committee field should be visible.
6. open participants and create a new user as a meeting admin
7. open a new browser and log in as the meeting admin
8. open motions > open the motion > edit submitters (new field should not be visible)
9. open the motion in edit mode and save it again
10. edit submitter. The field should now be visible. If not, click on extension and it should be visible. (Hint: Sometimes a click on the extension field is needed to see the committee field. Even after saving the motion again)
11. Now head back to the superadmin browser 
12. open participants > group permission menu > edit staff > grant permissions 'can see motions' and 'can manage motion metdadata' > save
13. open participants > change group of the meeting admin to staff
14. open the other browser and head to motions. open the motion and try to edit submitters. > committee field is not visible.

**What should happen:**

- [ ] All user which are allowed to edit submitters should see the committee field immediately. 
- [ ] User with the group permission 'can manage motion metadata' should be able to see and edit the committee field.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #3689

needs https://github.com/OpenSlides/openslides-backend/pull/2439

### CODE REVIEW

**Review by luisa-beerboom — COMMENTED** [review]
I see no style problems with the code, although I don't understand what it's supposed to do, as I don't recognize the feature this is supposed to be about.

**Comment by bastianjoel** [comment]
This fixes a bug in the committee selection of submitters in motions.

**Review by luisa-beerboom — APPROVED** [review]

**Review by MSoeb — CHANGES_REQUESTED** [review]
Discussed problems with @bastianjoel

**Comment by bastianjoel** [comment]
Committies not displayed when directly accessing a motion

**Review by MSoeb — APPROVED** [review]
The PR fixes the visibility of the committee selection as intended. But another problem occurs. Sometimes the committee selection field shows no option, even if it should have one. I've tried to debug and reproduce the error with @bastianjoel , but we found ne hint, what caused it. The only way to reproduce it is, to reload the page and check the field until the error appears.

Nevertheless, the PR will be approved because it fixes the issue.

**Pull request merged**
